<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\RateMatrix;

class RateMatrixSeeder extends Seeder
{
    public function run()
    {
        $rates = [
            // Tier 1 (0 Experience)
            [
                'experience_tier' => 1,
                'fico_min' => 660,
                'fico_max' => 679,
                'fico_range' => '660-679',
                'max_total_loan' => 0.00,
                'max_budget' => 0.00,
                'max_ltv_light' => 0.00,
                'max_ltc_light' => 0.00,
                'max_ltv_moderate' => 0.00,
                'max_ltc_moderate' => 0.00,
                'max_ltv_heavy' => 0.00,
                'max_ltc_heavy' => 0.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 0.000,
                'lender_points_base' => 0.000
            ],
            [
                'experience_tier' => 1,
                'fico_min' => 680,
                'fico_max' => 699,
                'fico_range' => '680-699',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 75.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 75.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 0.00,
                'max_ltc_heavy' => 0.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 1,
                'fico_min' => 700,
                'fico_max' => 719,
                'fico_range' => '700-719',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 75.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 75.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 0.00,
                'max_ltc_heavy' => 0.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.500,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 1,
                'fico_min' => 720,
                'fico_max' => 739,
                'fico_range' => '720-739',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 80.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 80.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 0.00,
                'max_ltc_heavy' => 0.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.000,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 1,
                'fico_min' => 740,
                'fico_max' => 850,
                'fico_range' => '740+',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 0.00,
                'max_ltc_heavy' => 0.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 11.500,
                'lender_points_base' => 2.500
            ],

            // Tier 2 (1-2 Experience)
            [
                'experience_tier' => 2,
                'fico_min' => 660,
                'fico_max' => 679,
                'fico_range' => '660-679',
                'max_total_loan' => 0.00,
                'max_budget' => 0.00,
                'max_ltv_light' => 0.00,
                'max_ltc_light' => 0.00,
                'max_ltv_moderate' => 0.00,
                'max_ltc_moderate' => 0.00,
                'max_ltv_heavy' => 0.00,
                'max_ltc_heavy' => 0.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.940
            ],
            [
                'experience_tier' => 2,
                'fico_min' => 680,
                'fico_max' => 699,
                'fico_range' => '680-699',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 80.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 80.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 75.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 2,
                'fico_min' => 700,
                'fico_max' => 719,
                'fico_range' => '700-719',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 80.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 80.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 75.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.500,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 2,
                'fico_min' => 720,
                'fico_max' => 739,
                'fico_range' => '720-739',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 80.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 80.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 75.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.000,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 2,
                'fico_min' => 740,
                'fico_max' => 850,
                'fico_range' => '740+',
                'max_total_loan' => 1000000.00,
                'max_budget' => 100000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 75.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 11.500,
                'lender_points_base' => 2.500
            ],

            // Tier 3 (3-4 Experience)
            [
                'experience_tier' => 3,
                'fico_min' => 660,
                'fico_max' => 679,
                'fico_range' => '660-679',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 85.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 85.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 80.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 0.00,
                'max_ltc_extensive' => 0.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 3,
                'fico_min' => 680,
                'fico_max' => 699,
                'fico_range' => '680-699',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 85.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 85.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 80.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 80.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 3,
                'fico_min' => 700,
                'fico_max' => 719,
                'fico_range' => '700-719',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 85.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 85.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 80.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 80.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.500,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 3,
                'fico_min' => 720,
                'fico_max' => 739,
                'fico_range' => '720-739',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 85.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 85.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 80.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 80.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.000,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 3,
                'fico_min' => 740,
                'fico_max' => 850,
                'fico_range' => '740+',
                'max_total_loan' => 2000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 80.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 80.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 11.500,
                'lender_points_base' => 2.500
            ],

            // Tier 4 (5-9 Experience)
            [
                'experience_tier' => 4,
                'fico_min' => 660,
                'fico_max' => 679,
                'fico_range' => '660-679',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 85.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 4,
                'fico_min' => 680,
                'fico_max' => 699,
                'fico_range' => '680-699',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 85.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 4,
                'fico_min' => 700,
                'fico_max' => 719,
                'fico_range' => '700-719',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 85.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.500,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 4,
                'fico_min' => 720,
                'fico_max' => 739,
                'fico_range' => '720-739',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 85.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.000,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 4,
                'fico_min' => 740,
                'fico_max' => 850,
                'fico_range' => '740+',
                'max_total_loan' => 2000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 85.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 11.500,
                'lender_points_base' => 2.500
            ],

            // Tier 5 (10+ Experience)
            [
                'experience_tier' => 5,
                'fico_min' => 660,
                'fico_max' => 679,
                'fico_range' => '660-679',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 90.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 5,
                'fico_min' => 680,
                'fico_max' => 699,
                'fico_range' => '680-699',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 90.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.750,
                'lender_points_base' => 2.990
            ],
            [
                'experience_tier' => 5,
                'fico_min' => 700,
                'fico_max' => 719,
                'fico_range' => '700-719',
                'max_total_loan' => 2000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 90.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.500,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 5,
                'fico_min' => 720,
                'fico_max' => 739,
                'fico_range' => '720-739',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 90.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 12.000,
                'lender_points_base' => 2.500
            ],
            [
                'experience_tier' => 5,
                'fico_min' => 740,
                'fico_max' => 850,
                'fico_range' => '740+',
                'max_total_loan' => 1000000.00,
                'max_budget' => 500000.00,
                'max_ltv_light' => 90.00,
                'max_ltc_light' => 75.00,
                'max_ltv_moderate' => 90.00,
                'max_ltc_moderate' => 75.00,
                'max_ltv_heavy' => 90.00,
                'max_ltc_heavy' => 75.00,
                'max_ltv_extensive' => 85.00,
                'max_ltc_extensive' => 75.00,
                'interest_rate_base' => 11.500,
                'lender_points_base' => 2.500
            ]
        ];

        foreach ($rates as $rate) {
            RateMatrix::create($rate);
        }
    }
}